### ISSUE TITLE
Macro fails on most recent FreCAD version

### ISSUE THREAD

**Issue by der-coder** [psicofil/Macros_FreeCAD#1]
Running the Macro outputs the following error:

Error!!, sorry..Traceback (most recent call last):
  File "/home/isaac/.FreeCAD/Macros/Macros/GMSHMesh.FCMacro", line 150, in proceed
    FreeCAD.Console.PrintMessage(output)
UnboundLocalError: local variable 'output' referenced before assignment

==== FreeCAd info: ====

OS: Linux
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.16.4856 (Git)
Branch: master
Hash: 3e82f69ca52e29642ec84fdc84ffc4e448d5c4d8
Python version: 2.7.9
Qt version: 4.8.6
Coin version: 3.1.3
OCC version: 6.8.0.oce-0.17

**Comment by psicofil** [comment]
Try testing the new version that includes a lot of fixes in the code by PrzemoF

**Comment by psicofil** [comment]
You have installed gmsh? the gmsh command should be available in the folder /usr/bin for the macro work. sorry for my bad English

**Comment by der-coder** [comment]
I'd like to close the issue. I fixed it by replacing the reference to gmsh to a hardcoded path.
